spring:
  application:
    name: orbit
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fundingboost}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    secret: ${JWT_SECRET}
    token-validity-time: ${JWT_TOKEN_VALIDITY_TIME}
