spring:
  application:
    name: fundingboost
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fundingboost}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        default-page-size: 10
        size-parameter: size
        page-parameter: page
  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    secret: ${JWT_SECRET}
    token-validity-time: ${JWT_TOKEN_VALIDITY_TIME}
iamport:
  api-key: ${PAY_API_KEY}
  secret-key: ${PAY_SECRET_KEY}
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}